# -*- coding: utf-8 -*-
"""Gerar Valores de Emoções para Análise Facial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9NQlCj_h2x6qjya-_pozADXtWruXOgo
"""

import csv
import random

# Definir as emoções e suas distribuições de atributos
emotions = {
    'Feliz': {
        'sorriso': (0.7, 1.0),
        'olho_esquerdo': (0.6, 1.0),
        'olho_direito': (0.6, 1.0),
        'angulo_x': (-10, 10),
        'angulo_y': (-10, 10),
        'angulo_z': (-10, 10),
        'boca_visivel_esq': 1,
        'boca_visivel_dir': 1,
        'olho_visivel_esq': 1,
        'olho_visivel_dir': 1,
        'nariz_visivel': 1
    },
    'Cansado': {
        'sorriso': (0.0, 0.3),
        'olho_esquerdo': (0.0, 0.5),
        'olho_direito': (0.0, 0.5),
        'angulo_x': (10, 30),
        'angulo_y': (-10, 10),
        'angulo_z': (-10, 10),
        'boca_visivel_esq': 1,
        'boca_visivel_dir': 1,
        'olho_visivel_esq': 1,
        'olho_visivel_dir': 1,
        'nariz_visivel': 1
    },
    'Neutro': {
        'sorriso': (0.3, 0.7),
        'olho_esquerdo': (0.4, 0.6),
        'olho_direito': (0.4, 0.6),
        'angulo_x': (-5, 5),
        'angulo_y': (-5, 5),
        'angulo_z': (-5, 5),
        'boca_visivel_esq': 1,
        'boca_visivel_dir': 1,
        'olho_visivel_esq': 1,
        'olho_visivel_dir': 1,
        'nariz_visivel': 1
    },
    'Estressado': {
        'sorriso': (0.0, 0.2),
        'olho_esquerdo': (0.5, 1.0),
        'olho_direito': (0.5, 1.0),
        'angulo_x': (-20, 20),
        'angulo_y': (-20, 20),
        'angulo_z': (-20, 20),
        'boca_visivel_esq': 1,
        'boca_visivel_dir': 1,
        'olho_visivel_esq': 1,
        'olho_visivel_dir': 1,
        'nariz_visivel': 1
    },
    'Ansioso': {
        'sorriso': (0.0, 0.2),
        'olho_esquerdo': (0.7, 1.0),
        'olho_direito': (0.7, 1.0),
        'angulo_x': (-15, 15),
        'angulo_y': (-15, 15),
        'angulo_z': (-15, 15),
        'boca_visivel_esq': 1,
        'boca_visivel_dir': 1,
        'olho_visivel_esq': 1,
        'olho_visivel_dir': 1,
        'nariz_visivel': 1
    }
}

# Número de amostras por emoção
samples_per_emotion = 1000

# Nome do arquivo CSV
filename = 'treinamento_humor_unimap.csv'

# Escrever o arquivo CSV
with open(filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    # Escrever o cabeçalho
    writer.writerow([
        'sorriso', 'olho_esquerdo', 'olho_direito',
        'angulo_x', 'angulo_y', 'angulo_z',
        'boca_visivel_esq', 'boca_visivel_dir',
        'olho_visivel_esq', 'olho_visivel_dir',
        'nariz_visivel', 'humor'
    ])
    # Gerar os dados
    for emotion, attrs in emotions.items():
        for _ in range(samples_per_emotion):
            row = [
                round(random.uniform(*attrs['sorriso']), 2),
                round(random.uniform(*attrs['olho_esquerdo']), 2),
                round(random.uniform(*attrs['olho_direito']), 2),
                round(random.uniform(*attrs['angulo_x']), 2),
                round(random.uniform(*attrs['angulo_y']), 2),
                round(random.uniform(*attrs['angulo_z']), 2),
                attrs['boca_visivel_esq'],
                attrs['boca_visivel_dir'],
                attrs['olho_visivel_esq'],
                attrs['olho_visivel_dir'],
                attrs['nariz_visivel'],
                emotion
            ]
            writer.writerow(row)

print(f'Dataset sintético gerado com sucesso: {filename}')